# Generated by Django 4.1.7 on 2023-08-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='telefon',
            field=models.IntegerField(null=True),
        ),
    ]
