# Generated by Django 4.1.7 on 2023-08-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_kategori_alter_hesap_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fiyat',
        ),
    ]
