# Generated by Django 4.1.7 on 2023-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_post_olusturan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesap',
            name='tarih',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='begenenler',
            field=models.JSONField(null=True),
        ),
    ]
