# Generated by Django 4.1.7 on 2023-08-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_hesap_tarih_post_begenenler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='begenenler',
        ),
    ]
