# Generated by Django 4.1.7 on 2023-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_post_begenenler'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='begenenler',
            field=models.JSONField(null=True),
        ),
    ]
