# Generated by Django 4.1.7 on 2023-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_post_begenenler_post_begenenler'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesap',
            name='profilResmi',
            field=models.FileField(null=True, upload_to='profil/'),
        ),
    ]
